/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jbenk;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateusz
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loggedInPanel.setVisible(false);
        browseAccountsPanel.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setSize(width, 140);
        try{
        GlobalVariables.Deserialize();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                  "Couldnt find accounts file !",
               "Error!",
                  JOptionPane.PLAIN_MESSAGE);
        }
      }
    int width = 265;
    int tempAccIndex=-1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loggedInPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accInformationTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        amountTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        logInPanel = new javax.swing.JPanel();
        browseButton = new javax.swing.JButton();
        LogInButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        accIDTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        browseAccountsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        browseAccountsComboBox = new javax.swing.JComboBox<String>();
        closeBrowserButton = new javax.swing.JButton();
        deleteSelectedAccButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        browseAccInformationTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jbenk");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loggedInPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loggedInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accInformationTextArea.setEditable(false);
        accInformationTextArea.setColumns(20);
        accInformationTextArea.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        accInformationTextArea.setRows(5);
        jScrollPane1.setViewportView(accInformationTextArea);

        loggedInPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 152));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Your Account Information");
        loggedInPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        loggedInPanel.add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        amountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountTextFieldFocusLost(evt);
            }
        });
        amountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountTextFieldKeyPressed(evt);
            }
        });
        loggedInPanel.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, -1));

        jLabel2.setText("Amount :");
        loggedInPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        loggedInPanel.add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 82, -1));

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        loggedInPanel.add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        getContentPane().add(loggedInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 312));

        logInPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        browseButton.setText("Browse Existing Accounts");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        LogInButton.setText("Log In");
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Create new Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        accIDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accIDTextFieldFocusLost(evt);
            }
        });
        accIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accIDTextFieldKeyPressed(evt);
            }
        });

        jLabel1.setText("Enter account ID :");

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(accIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(LogInButton))
                    .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(accIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(LogInButton))
                .addGap(6, 6, 6)
                .addComponent(browseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(logInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 110));

        browseAccountsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        browseAccountsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Existing Accounts :");
        browseAccountsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 13, -1, -1));

        browseAccountsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                browseAccountsComboBoxItemStateChanged(evt);
            }
        });
        browseAccountsPanel.add(browseAccountsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 8, 126, -1));

        closeBrowserButton.setText("Close");
        closeBrowserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBrowserButtonActionPerformed(evt);
            }
        });
        browseAccountsPanel.add(closeBrowserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 320, -1, -1));

        deleteSelectedAccButton.setText("Delete Selected Account");
        deleteSelectedAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedAccButtonActionPerformed(evt);
            }
        });
        browseAccountsPanel.add(deleteSelectedAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 320, -1, -1));

        browseAccInformationTextArea.setEditable(false);
        browseAccInformationTextArea.setColumns(20);
        browseAccInformationTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        browseAccInformationTextArea.setRows(5);
        jScrollPane2.setViewportView(browseAccInformationTextArea);

        browseAccountsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 142, -1, 148));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Selected Account Information");
        browseAccountsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 119, -1, -1));

        getContentPane().add(browseAccountsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 260, 422));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CreateAccountFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
       LogIn();
    }//GEN-LAST:event_LogInButtonActionPerformed

    
    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        amountTextField.setText("");
        tempAccIndex=-1;
        loggedInPanel.setVisible(false);
        logInPanel.setVisible(true);
        this.setSize(width, 140);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        try{
        if(tempAccIndex!=-1){
            double balance = GlobalVariables.Accounts.get(tempAccIndex).editBalance(-Double.valueOf(amountTextField.getText()));
            if(balance<0){
                JOptionPane.showMessageDialog(this,
                  "Your account balance is negative !",
               "Message!",
                  JOptionPane.PLAIN_MESSAGE);
            }
            GlobalVariables.Serialize();
            GlobalVariables.Accounts.get(tempAccIndex).insertInformation(accInformationTextArea);
        }else
            JOptionPane.showMessageDialog(this,
                  "Couldnt find accounts balance !",
               "Error!",
                  JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                  "Incorrect amount !",
               "Error!",
                  JOptionPane.PLAIN_MESSAGE);
            amountTextField.setText("");
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        try{
        if(tempAccIndex!=-1){
            double balance = GlobalVariables.Accounts.get(tempAccIndex).editBalance(Double.valueOf(amountTextField.getText()));
            if(balance<0){
                JOptionPane.showMessageDialog(this,
                  "Your account balance is negative !",
               "Message!",
                  JOptionPane.PLAIN_MESSAGE);
            }
            GlobalVariables.Serialize();
            GlobalVariables.Accounts.get(tempAccIndex).insertInformation(accInformationTextArea);
        }else
            JOptionPane.showMessageDialog(this,
                  "Couldnt find accounts balance !",
               "Error!",
                  JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                  "Incorrect amount !",
               "Error!",
                  JOptionPane.PLAIN_MESSAGE);
                        amountTextField.setText("");

        }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void accIDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accIDTextFieldKeyPressed
        accIDTextField.setText(accIDTextField.getText().replaceAll("[^0-9]",""));
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        LogIn();
    }//GEN-LAST:event_accIDTextFieldKeyPressed

    private void amountTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextFieldKeyPressed
        amountTextField.setText(amountTextField.getText().replaceAll(",", "."));

        amountTextField.setText(amountTextField.getText().replaceAll("[^\\d.]", ""));
    }//GEN-LAST:event_amountTextFieldKeyPressed

    private void amountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTextFieldFocusLost
        amountTextField.setText(amountTextField.getText().replaceAll(",", "."));

        amountTextField.setText(amountTextField.getText().replaceAll("[^\\d.]", ""));
    }//GEN-LAST:event_amountTextFieldFocusLost

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        browseAccountsPanel.setVisible(true);
        this.setSize(528, 421);
        browseAccountsComboBox.setSelectedIndex(-1);
        browseAccountsComboBox.removeAllItems();
        for(Account acc:GlobalVariables.Accounts)
        {
            browseAccountsComboBox.addItem(String.valueOf(acc.id));
            browseAccountsComboBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void closeBrowserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBrowserButtonActionPerformed
        browseAccInformationTextArea.setText("");
        browseAccountsComboBox.setSelectedIndex(-1);
        browseAccountsComboBox.removeAllItems();
        browseAccountsPanel.setVisible(false);
        if(loggedInPanel.isVisible())            
            this.setSize(width, this.getSize().height);
        else
            this.setSize(width, 140);
    }//GEN-LAST:event_closeBrowserButtonActionPerformed

    private void browseAccountsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_browseAccountsComboBoxItemStateChanged
        if(browseAccountsComboBox.getSelectedIndex()!=-1)
        {
            for(Account acc:GlobalVariables.Accounts)
            {
                if(browseAccountsComboBox.getSelectedItem().toString().equals(String.valueOf(acc.id)))
                    acc.insertInformation(browseAccInformationTextArea);
            }
        }
    }//GEN-LAST:event_browseAccountsComboBoxItemStateChanged

    private void deleteSelectedAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedAccButtonActionPerformed
        int tempIndex=0;
        for(Account acc:GlobalVariables.Accounts)
            {
                if(browseAccountsComboBox.getSelectedItem().toString().equals(String.valueOf(acc.id))){
                    GlobalVariables.Accounts.remove(acc);
                    break;
                }
            }
        GlobalVariables.Serialize();
    }//GEN-LAST:event_deleteSelectedAccButtonActionPerformed

    private void accIDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accIDTextFieldFocusLost
        accIDTextField.setText(accIDTextField.getText().replaceAll("[^0-9]",""));
    }//GEN-LAST:event_accIDTextFieldFocusLost
/*
    
    if(!amountTextField.getText().matches("^[0-9]+\\.?[0-9]*$")&&!amountTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,
                  "You can only type in digits and one dot.",
               "Try Again!",
                  JOptionPane.PLAIN_MESSAGE);
        }
    if(amountTextField.getText().indexOf(".", amountTextField.getText().indexOf(".") + 1)!=1)
        {
            amountTextField.setText(amountTextField.getText().substring(amountTextField.getText().indexOf(".", amountTextField.getText().indexOf(".") + 1),
                    amountTextField.getText().indexOf(".", amountTextField.getText().indexOf(".") + 1)));
        }
    */
    private void LogIn()
    {
         if(!accIDTextField.getText().equals(""))
        {
        boolean sucess=false;
        tempAccIndex=0;
        for(Account acc : GlobalVariables.Accounts)
        {
            if(String.valueOf(acc.id).equals(accIDTextField.getText()))
            {
                sucess=true;
                break;
            }
            tempAccIndex++;
        }
        if(sucess)
        {
            GlobalVariables.Accounts.get(tempAccIndex).insertInformation(accInformationTextArea);
            loggedInPanel.setVisible(true);
            accIDTextField.setText("");
            this.setSize(this.getSize().width, 451);
            amountTextField.setText("");
            
        }else{
            
            JOptionPane.showMessageDialog(this,
                  "An account with ID : "+ accIDTextField.getText() +" was not found !",
               "Fail!",
                  JOptionPane.PLAIN_MESSAGE);
            tempAccIndex=-1;
        }
        }else{
            JOptionPane.showMessageDialog(this,
                  "You need to insert Account ID to the Text Field!",
               "Fail!",
                  JOptionPane.PLAIN_MESSAGE);
         tempAccIndex=-1;
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInButton;
    private javax.swing.JTextField accIDTextField;
    private javax.swing.JTextArea accInformationTextArea;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JTextArea browseAccInformationTextArea;
    private javax.swing.JComboBox<String> browseAccountsComboBox;
    private javax.swing.JPanel browseAccountsPanel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton closeBrowserButton;
    private javax.swing.JButton deleteSelectedAccButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel loggedInPanel;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
